services:
  user_session_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: user_session_db
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    volumes:
      - ./user_session_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user_session_data:/var/lib/mysql
    networks:
      - app_network
    restart: always

  stock_prediction_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stock_prediction_db
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    volumes:
      - ./stock_prediction_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - stock_prediction_data:/var/lib/mysql
    networks:
      - app_network
    restart: always
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: ethanjameslong1/frontend:latest
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      finet:
        condition: service_started
      analysis:
        condition: service_started

  finet:
    build:
      context: ..
      dockerfile: ./cmd/finet/dockerfile/finetDockerfile
    image: ethanjameslong1/finet:latest
    expose:
      - "8000"
    environment:
      DB_USER_SESSION_HOST: user_session_db
      DB_USER_SESSION_PORT: 3306
      DB_USER_SESSION_NAME: user_session_db
      DB_STOCK_PREDICTION_HOST: stock_prediction_db
      DB_STOCK_PREDICTION_PORT: 3306
      DB_STOCK_PREDICTION_NAME: stock_prediction_db
    networks:
      - app_network
    depends_on:
      user_session_db:
        condition: service_started
      stock_prediction_db:
        condition: service_started
    restart: always

  analysis:
    build:
      context: ..
      dockerfile: ./cmd/stock/dockerfile/stockDockerfile
    image: ethanjameslong1/analysis:latest
    expose:
      - "8001"
    environment:
      DB_STOCK_PREDICTION_HOST: stock_prediction_db
      DB_STOCK_PREDICTION_PORT: 3306
      DB_STOCK_PREDICTION_NAME: stock_prediction_db
      API_KEY: ${API_KEY}
    networks:
      - app_network
    depends_on:
      user_session_db:
        condition: service_started
      stock_prediction_db:
        condition: service_started

volumes:
  user_session_data:
  stock_prediction_data:

networks:
  app_network:
    driver: bridge


